environment: production

logging:
  level:
    root: INFO

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5431/se452db
    username: postgres
    password: password
    data: classpath:/data.sql