environment: production

logging:
  level:
    root: ERROR

spring:
  jpa:
    generate-ddl: true
    show-sql: true
    defer-datasource-initialization: true
  datasource:
    url: jdbc:postgresql://localhost:5432/se452
    username: postgres
    password: password