version: '3.8'

services:
    app:
        container_name: app
        image: shoebsmk/group2application
        env_file: ./.env
        ports:
            - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"
            
        