#Be sure to change volumn location
#start:   docker-compose -f docker-sql.yml up -d
#stop:    docker-compse -f docker-sql.yml down

version: '3.8'
services:
    postgresql:
      container_name: demo-postgres
      image: postgres
      env_file: ./.env
      volumes: 
          - "$POSTGRES_EXTERNAL_LOC:/var/lib/postgresql/data"
      restart: always
      ports:
          - $POSTGRES_PORT:$POSTGRES_PORT
      environment:
          POSTGRES_PASSWORD: password
    app:
      depends_on: 
        - postgresql
      container_name: group2application
      image: shoebsmk/group2application
      env_file: ./.env
      ports:
          - "$SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT"    
      environment:
        SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:postgresql://postgresql:$POSTGRES_PORT/$SQL_DB",
            "spring.datasource.username" : "$SQL_USER",
            "spring.datasource.password" : "$SQL_PASSWORD",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'         